### ISSUE TITLE
Loom fails to rename LootTable.pools on forge

### ISSUE THREAD

**Issue by EdwinMindcraft** [architectury/architectury-loom#11]
When using forge and official mappings, the field pools in LootTable isn't renamed.
This is most likely due to [this patch](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/loot/LootTable.java.patch#L8) that changes the type of the field.
The main consequence is that forge's ObfuscationReflectionHelper may be broken (breaks with Quark-r2.4-308).

**Comment by shedaniel** [comment]
To add to this, there are more fields that match this description. Like KeyMapping.MAP

**Comment by shedaniel** [comment]
Fixed in 0.7.2-SNAPSHOT
