### ISSUE TITLE
How to load a mod in a subproject as a dependency? 

### ISSUE THREAD

**Issue by qyl27** [architectury/architectury-loom#120]
I have some subproject in a gradle project, they are all forge mods, and they used architectury loom.  
I want made SinoCore(Subproject A) loaded when I tried to launch SinoCalligraphy(Subproject B) client for debugging.  
I got SinoCalligraphy(Subproject B) loaded only.  
I have tried [FabricMC/fabric-loom#746](https://github.com/FabricMC/fabric-loom/issues/746), but it not working for me.  
So is there any solution?  

Link:  
[My Project Repo](https://github.com/SinoCraftProject/SinoSeries/tree/855ffeded8c9dc1297d0383bc63d604c9f7370da)

**Comment by Juuxel** [comment]
On Forge you also must declare a local mod for subproject A in subproject B like this (it's optional in most cases on Fabric):
```gradle
evaluationDependsOn ':SinoCore' // needed so the projects get configured in the right order

loom {
    mods {
        sinocore {
            sourceSet project(':SinoCore').sourceSets.main
        }
    }
}
```

**Comment by qyl27** [comment]
Oh, it works! Thanks a lot.
