### ISSUE TITLE
Adding JEI as dependency cause runtime ClassNotFoundException.

### ISSUE THREAD

**Issue by qyl27** [architectury/architectury-loom#123]
I have a multi-project forge mod, when I tried to add JEI to root project as dependency, run client, it cause a runtime ClassNotFoundException.   
Seems like it add only the forge module of JEI. (I have followed the JEI wiki to modify my build.gradle.) It shows can not found `mezz.jei.common.xxx`.  
I have tried to set the `transitive` option of the dependency to `true` or change `modRuntimeOnly` to `modImplementation`, but helps nothing.  

[My Project https://github.com/SinoCraftProject/SinoSeries/tree/dev/add-jei-for-debug](https://github.com/SinoCraftProject/SinoSeries/tree/dev/add-jei-for-debug)

**Comment by embeddedt** [comment]
I ran into this as well. My simple workaround was to compile-time depend on JEI the proper way but use the JAR from CurseForge via CurseMaven for runtime.

**Comment by shedaniel** [comment]
You need to set all JEI dependencies to transitive false, and also remember to clean the loom remap cache by deleting the .gradle folder in your project.
