### ISSUE TITLE
forge dependencies that use JarinJar don't get remapped 

### ISSUE THREAD

**Issue by KP2048** [architectury/architectury-loom#125]
the specific mod in question is this
https://github.com/thedarkcolour/KotlinForForge
from what i can tell, the structure of the jars is this:
root jar
| kotlin library stuff
| mod jar
| - actual mod that needs to be remapped
| forge language extention jar
| - contains the stuff forge looks for to be able to load kotlin based mods
| kotlin lib jar
| - contains the forge specific kotlin stuff

essentially, that mod jar doesn't get remapped, only the root jar, which isn't even really a mod. moreover, the inner jars don't even get added to the external libraries list in my ide, but if i use the modApiMapped one, they do show up, but they aren't mapped and so don't load correctly when i start the game

**Comment by Juuxel** [comment]
Not relevant after #159.
