### ISSUE TITLE
Are there any Minecraft data generator support?

### ISSUE THREAD

**Issue by qyl27** [architectury/architectury-loom#131]
In the migration of a forge mod, I need some support about Minecraft (or forge provided) Data Generator.  
Any plan about it?

**Comment by Juuxel** [comment]
Data generators can be used on both Fabric and Forge in projects using Architectury Loom.

Instructions for Fabric: https://fabricmc.net/wiki/tutorial:datagen_setup
Instructions for Forge: https://docs.architectury.dev/loom/datagen
