### ISSUE TITLE
AccessWidenerFormatException Namespace mismatch

### ISSUE THREAD

**Issue by rlnt** [architectury/architectury-loom#136]
- Minecraft: 1.19.2
- Architectury Plugin: 3.4.146
- Architectury Loom: 1.2.342
- Fabric Loader: 0.14.19
- Fabric Api: 0.76.0
- Gradle: 8.1.1

After upgrading to Gradle 8.1+ and Arch Loom 1.2+, there is an `AccessWidenerFormatException` when starting the Fabric client within the IDE.
```
AccessWidenerFormatException: Namespace (intermediary) does not match current runtime namespace (named)
```
![](https://i.imgur.com/NWlIJ4U.png)

It happens when you depend on a mod that has an AW. It doesn't matter whether you use
```
modCompileOnly(modLocalRuntime("fooBar")!!)
```
or
```
modApi("fooBar")
```
It also doesn't matter whether the dependency mod uses Arch Loom 1.2 or 0.12.
It can only be reproduced when the mod that uses the dependency is on Arch Loom 1.2 (side note: it also happens on 1.1) and a somewhat recent version of Fabric loader. Use the versions mentioned above to be able to reproduce it.

This issue was reproduced and confirmed by @MaxNeedsSnacks when depending on the Arch Loom 1.2 version of KubeJS.

**Comment by Juuxel** [comment]
Fixed in #140.
