### ISSUE TITLE
Forge built-in JS coremods are not remapped

### ISSUE THREAD

**Issue by Su5eD** [architectury/architectury-loom#146]
It appears that while architectury loom is capable of remapping js coremods in mod dependencies, it doesn't do so for forge itself. This leads to further issues at runtime.

### Steps to reproduce

1. Download the 1.19.4 forge architectury template from the [template repo](https://github.com/architectury/architectury-templates/releases/download/release_build_1681557561530/1.19.4-forge.zip).
2. Set the mappings to yarn
    ```gradle
    dependencies {
        mappings "net.fabricmc:yarn:1.19.4+build.2:v2"
    }
    ```
3. Import and setup the project
4. Open the `field_to_method.js` coremod inside the forge jar.
5. Observe that the contained class names are still in srg, and therefore the coremod won't be applied at runtime.

### Expected behavior

Forge coremod target names are remapped to yarn so that they can be applied.

**Comment by Su5eD** [comment]
P.S.: This should probably also be applied in remapJar to remap any coremods in the project itself.

**Comment by wagyourtail** [comment]
Iirc, These should get remapped at runtime using the forge service for doing so when in dev with the arch provider for that to use tiny mappings

**Comment by Su5eD** [comment]
That's correct, but unfortunately runtime target remapping of JS coremods is limited to method and field names. While modlauncher's name mapping service is set up correctly to map SRG -> YARN for all types, the JS coremod api doesn't support renaming class names or descriptors. 

- https://github.com/MinecraftForge/CoreMods/issues/25
- [`net.minecraftforge.coremod.CoreMod#buildCore`](https://github.com/MinecraftForge/CoreMods/blob/master/src/main/java/net/minecraftforge/coremod/CoreMod.java#L76-L80)

###### TBH I'm a little surprised how long this issue's been around, given the fix is quite trivial.

In an ideal situation, we wouldn't need to touch coremod files at all, since all remapping would be done at runtime. I believe this issue is what led to the implementation of `CoreModClassRemapper`.  
Right now, my only option in a forge yarn environment is writing all JS coremods in yarn and then remapping them to srg when building the project. Or perhaps I could migrate the coremod logic to a mixin plugin instead.
