### ISSUE TITLE
How can I apply AT's `public-f` option to a final method?

### ISSUE THREAD

**Issue by qyl27** [architectury/architectury-loom#147]
When I want to apply access transformer `public-f` to a final method, I use `genForgePatchedSources`, but it always shows `Cannot run Forge's patched decompilation with a processed Minecraft jar`, then failed.

How can I apply AT's `public-f` option to a final method?

**Comment by Juuxel** [comment]
Applying an AT processes the Minecraft jar further, so it's currently not possible to use `genForgePatchedSources` with it. This is intentional as it would interfere with Forge's patches.

You can use the default `genSources` task instead.
