### ISSUE TITLE
Order of `jars` in fabric.mod.json depends on HashSet iteration order

### ISSUE THREAD

**Issue by Johni0702** [architectury/architectury-loom#155]
And as such prevents builds which include more than one jar from being reliably reproducible.

https://github.com/architectury/architectury-loom/blob/3019b32fd738d2daf61bcc23a5b29abcc10a827d/src/main/java/net/fabricmc/loom/task/RemapJarTask.java#L434-L436

This doesn't affect the file order within the jar because upstream loom already re-sorts the entire jar at the end of the RemapJarTask, it's only the json which has a chance of being different each build. Also not an issue with upstream loom because it doesn't need to combine regular and forge jij lists.

**Comment by Juuxel** [comment]
Should be easy to fix with `LinkedHashSet`, I believe.
