### ISSUE TITLE
Regarding the issue that Neo Forge and Forge could not be developed at the same time

### ISSUE THREAD

**Issue by baka4n** [architectury/architectury-loom#160]
The key problem is that forge and neoforge cannot be developed together
If the maven of neo forge is placed in the front, the maven library file of forge cannot be found.
If forge's maven is placed in front, neoforge's maven library file cannot be found.

**Comment by Juuxel** [comment]
Using Forge and NeoForge in a single Gradle project is not supported. (You can have them in two different subprojects, however.)

If you need something from a specific repository, you can use Gradle's repository content filters and the "exclusive content" functionality.
