### ISSUE TITLE
Forge import hybrid jar `RuntimeException: Namespace mismatch, expected srg got intermediary`

### ISSUE THREAD

**Issue by SettingDust** [architectury/architectury-loom#165]
A fabric + forge hybrid jar import by gradle will cause wrong namespace since there is AW in jar but not srg namespace

**Comment by Juuxel** [comment]
Those jars are not supported by the Architectury toolchain. An AW in the wrong namespace, even if it's in a Forge jar, is going to crash.

To be more specific, mods used as dependencies on Forge should not contain fabric.mod.json files as Loom is going to process Fabric-specific contents such as access wideners in the Forge context.
