### ISSUE TITLE
MixinExtras annotations not being remapped on NeoForge

### ISSUE THREAD

**Issue by Fourmisain** [architectury/architectury-loom#174]
I hope I'm at the right place here.
I'm using [MixinExtras](https://github.com/LlamaLad7/MixinExtras) on a common/fabric/forge/neoforge project with yarn mappings and mixins in common.

As I understand, refmaps are now gone from NeoForge, so the mixin annotations are remapped directly instead.
This works without issue for standard annotations like `@Inject`, but fails for MixinExtras annotations.

For example, in
`@ModifyExpressionValue(method = "postHit", at = @At(value = "CONSTANT", args = "intValue=2"))`
the `"postHit"` will be left as-is, instead of being remapped to `"hurtEnemy(Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/entity/LivingEntity;Lnet/minecraft/world/entity/LivingEntity;)Z"`.

So far I've found two possible workarounds:
 - duplicate the offending mixin and manually change the annotations
 - switch the whole project over to mojmaps

**Comment by Juuxel** [comment]
This is a known issue with Tiny Remapper's mixin extension that will also need to be addressed upstream if Fabric ever wants to disable the mixin AP by default.

**Comment by Faboslav** [comment]
Any plans for this?

**Comment by Juuxel** [comment]
Yes, we'll have to downstream some TR and Loom 1.5 changes but the upstream work for it is done.

**Comment by Fourmisain** [comment]
Whoo, it's fixed! :tada:
Already compiling and working, thank you!
