### ISSUE TITLE
the forge mod don't access widener from intermediary

### ISSUE THREAD

**Issue by baka4n** [architectury/architectury-loom#177]
loom version 1.4-SNAPSHOT

can -> modImplementation "earth.terrarium.adastra:ad_astra-forge-1.19.2:1.12.7"

Failed to setup Minecraft, java.lang.IllegalArgumentException: Cannot remap access widener from namespace 'srg'. Expected: 'intermediary'

**Comment by Juuxel** [comment]
The Ad Astra jar is broken and contains an access widener + fabric.mod.json/architectury.common.json/quilt.mod.json (one of them) pointing to it, which shouldn't be the case with Forge mods.
