### ISSUE TITLE
Aw2At is only setup for the default `remapJar` task

### ISSUE THREAD

**Issue by MattSturgeon** [architectury/architectury-loom#187]
The [current code](https://github.com/architectury/architectury-loom/blob/1ea6b89130d0bdc7abfc9f073a382bb327084b6e/src/main/java/net/fabricmc/loom/task/RemapTaskConfiguration.java#L109) calls `Aw2At.setup(getProject(), remapJarTask)`, however if additional `RemapJarTask`s are configured, they get missed.

Perhaps `Aw2At.setup` should be called for all tasks `withType(RemapJarTask)`?

**Comment by Juuxel** [comment]
This is intentional behaviour and matches other extension methods only configuring the default task.

**Comment by MattSturgeon** [comment]
Using `atAccessWideners.add()`  in my custom `RemapJarTask`s solves my issue better than calling `Aw2At.setup()` for each task.
