### ISSUE TITLE
How to create a multi-subproject project with only one minecraft dependency?

### ISSUE THREAD

**Issue by qyl27** [architectury/architectury-loom#190]
I have a project split into some sub-mods.  
I found each sub-mod has an independent Minecraft dependency although they are the same Minecraft version and the same loader type(forge or fabric).  
The development environment setup took too long time.  
So is there any way can I optimize it?

**Comment by Juuxel** [comment]
With Loom 1.4, jars with the same content (mappings + MC version + mod loader + jar processors from AT/AW and dependencies) should be combined even when they're project-specific.

Note that jar processors can change based on what dependencies you have that contain transitive access wideners or injected interfaces.
