### ISSUE TITLE
Dependency remap breaks dependency

### ISSUE THREAD

**Issue by slava110** [architectury/architectury-loom#192]
Hi. I've added GeckoLib mod as dependency for my Forge project. However, my game wasn't starting. I was wondering why and found out that `META-INF/jarjar/metadata.json` file isn't present in *remapped* jar. It exists in jar obtained from maven, but after remapping it disappears. Maybe this error has something to do with it:
[log.txt](https://github.com/architectury/architectury-loom/files/13964994/log.txt)
Dependency (from repo: `https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/`):
```
modImplementation("software.bernie.geckolib:geckolib-forge-1.20.1:4.4")
```
I'm using:
`minecraft`: `1.20.1`
`forge`: `1.20.1-47.2.20`
`dev.architectury.loom`: `1.4-SNAPSHOT`

**Comment by Jab125** [comment]
Jar in Jar'd mods are removed on remap.
Geckolib should add the JiJ'd dependency as a normal dependency.

**Comment by slava110** [comment]
There is normal dependency but it doesn't load in the game.
I'm adding it using
```kotlin
implementation("com.eliotlash.mclib:mclib:20")
```
But when I launch my game in dev environment I'm getting
![image](https://github.com/architectury/architectury-loom/assets/26705162/257421f9-1dd6-4af1-921b-7831201fddc9)

Is there any reason why jar-in-jar mods are removed on remap? Also why only metadata is removed on remap, not the actual jar file inside `META-INF/jarjar` directory?

**Comment by Jab125** [comment]
consistency with fabric mods getting their JiJ'd files removed probably

**Comment by Juuxel** [comment]
> Is there any reason why jar-in-jar mods are removed on remap? Also why only metadata is removed on remap, not the actual jar file inside `META-INF/jarjar` directory?

Both are done for consistency with Fabric. (Deleting the actual jars isn't necessary here, it's easier to remove the metadata file.)

Jar-in-jar deps are also not easy to remap, so they are removed to fix issues such as #125. See #159.

**Comment by slava110** [comment]
Is it possible for it to leave dependency if it isn't obfuscated? I think there is JSON property in `metadata.json` to specify if dependency is obfuscated or not

**Comment by Juuxel** [comment]
No, since all dependencies should still be available as their normal variants in the mod's POM file. This is for consistency between different platforms.
