### ISSUE TITLE
[Features]Implement interface injection support?

### ISSUE THREAD

**Issue by baka4n** [architectury/architectury-loom#198]
[such as](https://fabricmc.net/wiki/tutorial:interface_injection)

**Comment by baka4n** [comment]
Let forge support this syntactic sugar as well

**Comment by baka4n** [comment]
I found the wiki and nothing happened

**Comment by Gaming32** [comment]
It's supported. Put it in [architectury.common.json](https://github.com/Gaming32/bingo/blob/main/common/src/main/resources/architectury.common.json).

**Comment by shedaniel** [comment]
https://docs.architectury.dev/loom/architectury_common_json

**Comment by baka4n** [comment]
Thanks, but the source doesn't show what kind of genre it is

**Comment by baka4n** [comment]
![1708827965139](https://github.com/architectury/architectury-loom/assets/60695447/374fcb19-aa78-459d-b710-b6971f2a641f)
![image](https://github.com/architectury/architectury-loom/assets/60695447/2a082f58-dcce-425e-ad39-4edfb5447264)

**Comment by baka4n** [comment]
oh! no custom!
