### ISSUE TITLE
Project using architectury loom fails to run a forge game instance in 1.15.2

### ISSUE THREAD

**Issue by Trikzon** [architectury/architectury-loom#20]
When running `Minecraft Client (:forge)`, the game fails to finish loading with the following error: 
> Forge (forge) has failed to load correctly

A full log is available here: https://gist.github.com/Trikzon/df7831a9ac55de6c62b140b8deb97a5b

When the mod is built, the built jar works in a non-dev environment.
This is the workspace I am using and getting the error with: https://github.com/trikzon/armor-visibility/tree/1.15.2

**Comment by shedaniel** [comment]
As a temporary solution you can set the FORGE_VERSION environment variable

**Comment by Trikzon** [comment]
That doesn't seem to be working for me, but I personally don't need it to work right now. I look forward to a fix

**Comment by shedaniel** [comment]
Fixed in #34
