### ISSUE TITLE
unfixable conflicts with NeoForge

### ISSUE THREAD

**Issue by TexBlock** [architectury/architectury-loom#214]
Minecrft: 1.20.6
Yarn Mappings: 1.20.6+build.1
NeoForge: 20.6.14-beta

1.20.5 have same issue

log: https://pastebin.com/VAusXWuE

**Comment by Jab125** [comment]
> If you are getting mapping conflicts when using Yarn, you may need to apply patches to Yarn.\nAn example on how to apply them is shown here: 
```groovy
mappings loom.layered {
  it.mappings("net.fabricmc:yarn:1.20.5+build.1:v2")
  it.mappings("dev.architectury:yarn-mappings-patch-neoforge:1.20.5+build.3")
}
```
