### ISSUE TITLE
Support for Forge 1.20.6

### ISSUE THREAD

**Issue by VidTu** [architectury/architectury-loom#216]
Forge 1.20.6 uses Mojmap (AFAIK) in runtime, current "forge" provider doesn't account for that.

**Comment by VidTu** [comment]
...and 1.21 i guess.
p.s. for people looking forward to this, it's already in progress by another person (thanks!), check out #219

**Comment by teddyxlandlee** [comment]
Lex has just confirmed that on Forgecord.

I guess no remap is required, or perform a fake remap like what `neoforge` does
