### ISSUE TITLE
Access Widener reference in architectury.common.json staying present when converted to Access Transformer

### ISSUE THREAD

**Issue by ThePandaOliver** [architectury/architectury-loom#223]
Im getting this error when i add a library mod im maintaining as a dependency to another project.
```
Cause: <library mod id>.accesswidener
```
```
A problem occurred configuring project ':neoforge'.
> Failed to setup Minecraft, java.io.IOException: Failed to process jar when running jar processor: fabric-loom:access-widener
```
This issue happens because on NeoForge (Probably Forge too) the access widener file is removed/replaced by the access transformer. It makes sense that its removed because its not usable anymore, but in the `architectury.common.json` the reference to the access widener still exists. This is not a problem when the mod has been build and isn't used in a development environment, if it is used in a development environment, then this error is caused. I have seen people fix this issue by excluding the `architectury.common.json` from the jar, but this will not work because i need the interface injection from `architectury.common.json` to stay.

I have made a fix for this issue myself in my build script. The code removes the reference to the access widener from the `architectury.common.json` before the mod has been packaged.
```
tasks.register("removeAWfromArchitecturyJson") {
	doLast {
		def jsonFile = file("$buildDir/resources/main/architectury.common.json")

		if (jsonFile.exists()) {
			def jsonContent = new JsonSlurper().parse(jsonFile)

			jsonContent.remove("accessWidener")
			jsonFile.write(new JsonBuilder(jsonContent).toPrettyString())
		}
	}
}

jar {
	dependsOn removeAWfromArchitecturyJson
}
```
I have not found any fault with the code yet.

**Comment by ThePandaOliver** [comment]
Btw im using architectury loom version 1.7, but it has been a problem since 1.6.
I have not tested forge yet.

**Comment by Jab125** [comment]
You are not supposed to have `architectury.common.json` in your built jars at all

**Comment by ThePandaOliver** [comment]
If i exclude the `architectury.common.json` from the built jars, the the interface injection doesn't work when the library is added as a dependency. Feel free to take a look at my repository to see if im doing something wrong [https://github.com/PandaDap2006/PandaLib/tree/Experimental/Multi-Version-project](https://github.com/PandaDap2006/PandaLib/tree/Experimental/Multi-Version-project).

**Comment by Jab125** [comment]
> If i exclude the `architectury.common.json` from the built jars, the the interface injection doesn't work when the library is added as a dependency. Feel free to take a look at my repository to see if im doing something wrong [https://github.com/PandaDap2006/PandaLib/tree/Experimental/Multi-Version-project](https://github.com/PandaDap2006/PandaLib/tree/Experimental/Multi-Version-project).

That's intentional. A Forge/NeoForge built jar shouldn't have interface injections. Only the common jar is supposed to have it.

**Comment by ThePandaOliver** [comment]
ahh, thanks for clearing that up for me, i guess i will close this issue then.
