### ISSUE TITLE
Subprojects do not copy common resources on runClient

### ISSUE THREAD

**Issue by rinOfTheStars** [architectury/architectury-loom#228]
Resources from the common project are _not_ copied into the `build/resources` directories of platform subprojects when running the subprojects' respective `LOADER/loom/runClient` tasks. This isn't an immediate problem on (neo)forge as mixins are copied by the gradle scripts, but fabric and quilt expect the common mixin json which does not exist for them to use at runtime. 

Intriguingly, this does not appear to be an issue in the compiled version of the mods—this might be an issue with the template buildscripts specifically? Not sure, tell me if I need to move this issue to that repo if that's the case

**Comment by rinOfTheStars** [comment]
~~Appears to be a duplicate of https://github.com/architectury/architectury-templates/issues/30, closing for now~~
Actually wait, no, this issue is a superset of that one. Oops.

**Comment by rhysdh540** [comment]
I don't think this is a loom issue, you just need to depend on the right output of the common module, like what happens here:
https://github.com/architectury/template-generator/blob/dev/src/templates/fabric/build.gradle#L38C5-L38C69

**Comment by rinOfTheStars** [comment]
That's already present in the buildscripts, yet the issue happens regardless

**Comment by rinOfTheStars** [comment]
Seems like the issue might be that the `transformProductionForge` and `transformProductionQuilt` tasks aren't being run as part of `runClient` (and presumably `runServer`), meaning this is for sure a buildscript issue.

**Comment by rinOfTheStars** [comment]
Maybe it isn't a buildscript issue, actually? I have no clue at this point...
