### ISSUE TITLE
Failed to genSource when aw contains forge/neoforge class/member in loom 1.7.

### ISSUE THREAD

**Issue by qyl27** [architectury/architectury-loom#229]
Architect Plugin: 3.4.159
Architectury Loom: 1.7.412

Logs: 
```text
> Task :sinodeco:sinodeco-forge:genSourcesWithVineflower FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sinodeco:sinodeco-forge:genSourcesWithVineflower'.
> Failed to decompile, java.lang.IllegalArgumentException: lineMap is empty
```

**Comment by qyl27** [comment]
It will happen when the aw includes a line about forge or neoforge, it can be reproduced in loom 1.7 and any Minecraft version.  

And works well in loom 1.6.

**Comment by Juuxel** [comment]
Access wideners to Forge/Neo aren't supported – it's very possible that they break something else too. I think accessor mixins might work better instead.
