### ISSUE TITLE
Access wideners on Forge

### ISSUE THREAD

**Issue by Juuxel** [architectury/architectury-loom#23]
AW files can be transformed into ATs on build (haha yes `RemapJarTask` bloat). This is *very* low priority, but would allow using essentially the same file on both platforms. (I also happen to like the AW format more as a personal opinion)

**Comment by canitzp** [comment]
I very much appreciate this idea 👍.
Aw can be placed in the common module then, makes it easier for all

**Comment by shedaniel** [comment]
Added with #24
