### ISSUE TITLE
Yarn Mappings Unfixable conflicts NeoForge

### ISSUE THREAD

**Issue by MoYingJi** [architectury/architectury-loom#230]
> Configure project :neoforge
Mapping target name conflicts detected:
  METHODs chi/[gU, getInventory]()Lbqk; -> getInventory
  METHODs fhy/[renderHotbar, m](Lfhz;Lfgf;)V -> renderHotbar
There were unfixable conflicts.

yarn_mappings = 1.21.1+build.3
neoforge_version = 21.1.21
id "dev.architectury.loom" version "1.7-SNAPSHOT" apply false

**Comment by Juuxel** [comment]
This is fixed by applying the [Yarn compat patch](https://github.com/architectury/yarn-mappings-patch).

Replace your `mappings` dependency with this:
```gradle
dependencies {
    mappings loom.layered {
        it.mappings("net.fabricmc:yarn:$rootProject.yarn_mappings:v2")
        it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$rootProject.yarn_mappings_patch_neoforge_version")
    }
}
```
and add the following to your gradle.properties:
```properties
yarn_mappings_patch_neoforge_version = 1.21+build.4
```
