### ISSUE TITLE
`NEW` `@At` targets fail to remap without the mixin AP

### ISSUE THREAD

**Issue by AnAwesomGuy** [architectury/architectury-loom#231]
so i have this mixin:
```java
@Mixin(Blocks.class)
public abstract class BlocksMixin {
    @Redirect(
        method = "<clinit>", at = @At(value = "NEW", target = "net/minecraft/world/level/block/Block", ordinal = 0),
        slice = @Slice(from = @At(value = "CONSTANT", args = "stringValue=bedrock"))
    )
    private static Block breakingbedrock$replaceBedrock(Properties properties) {
        return new BedrockBlock(properties.strength(BreakingBedrock.DESTROY_TIME, BreakingBedrock.EXPLOSION_RESIST));
    }
}
```

it works fine in dev, and also in prod normally

however, when i disable the mixin ap by adding `loom.mixin.useLegacyMixinAp = false` into my common `build.gradle` (the mixin is in common), the `net/minecraft/world/level/block/Block` doesnt remap properly and the mixin fails to inject in prod

the target also maps perfectly fine on normal fabric loom, which is very odd

arch loom version `1.7-SNAPSHOT` (`1.7.412`) and arch plugin `3.4-SNAPSHOT` (`3.4.159`)

**Comment by Juuxel** [comment]
I can't reproduce this issue on 1.9. If you have a minimal reproduction case, I can see if it still breaks and reopen the issue if that's the case.
