### ISSUE TITLE
Something's very wrong with fabric

### ISSUE THREAD

**Issue by DRD2k8** [architectury/architectury-loom#233]
Something is very wrong with the fabric side of architectury, first it says, "<Mod Project Goes Here<M>>\fabric\build\loom-cache\remapped_working\loom_mappings_1_20_1_layered_hash_40545_v2.net.fabricmc.fabric-api-fabric-client-tags-api-v1-1.1.2+1802ada577.jar: The process cannot access the file because it is being used by another process", then gradle says "Configuring projects" for WAY too long! And it says that the project ':fabric' has been held by pid! What's the problem?

**Comment by Jab125** [comment]
Looks like gradle crashed which means that the lock files weren't removed correctly.

Are you on the latest version of loom?

**Comment by DRD2k8** [comment]
Yes

**Comment by Xelbayria** [comment]
I had a similar problem. There is a workaround to fix this: delete `~/.gradle/cache/...` and start up IDEA. so far it's working for me.

**Comment by DRD2k8** [comment]
It worked. Thanks.
