### ISSUE TITLE
Unable to apply multiple AWs from different Subprojects

### ISSUE THREAD

**Issue by Charismara** [architectury/architectury-loom#235]
Arch loom seems to only apply one AWs from a different subproject instead of all. I ran into this issue while working on [my Lib Mod](https://github.com/ManasMods/ManasCore/tree/1.21.1/port-inventory-tabs) which is split in multiple small modules.

# My Setup
I got multiple modules and each module as their own `common`, `fabric` and `neoforge` gradle subprojects. There is one `testing` module which includes all other modules. The the common testing project defines those inclusions using the following code:

```gradle
ext {
    includedProjects = [
            ":network",
            ":storage",
            ":inventory"
    ]
}

loom {
    mods {
        includedProjects.forEach {
            def moduleProject = project("$it-common")
            register(moduleProject.name) {
                sourceSet("main", moduleProject)
            }
        }
    }
}

dependencies {
    includedProjects.forEach {
        implementation(project(path: "$it-common", configuration: 'namedElements')) { transitive false }
    }
}
```

the testing `fabric` and `neoforge` subprojects use the `includedProjects` prob to include the correct module subproject to the runtime

```gradle
loom {
    mods {
        project(":testing-common").includedProjects.forEach {
            def moduleProject = project("$it-neoforge")
            register(moduleProject.name) {
                sourceSet("main", moduleProject)
            }
        }
    }
}

dependencies {
    project(":testing-common").includedProjects.forEach {
        common(project(path: "$it-common", configuration: 'namedElements')) { transitive false }
        implementation(project(path: "$it-fabric", configuration: 'namedElements')) // For fabric only
        implementation(project(path: "$it-neoforge", configuration: 'namedElements')) { transitive false } // For neoforge only
    }
}
```

This setup work when only the first included module (in this case `network`) contains an AW and no other project. The AWs of the other modules won't get applied. When removing `network` from the `includedProjects` the next existing AW in that list will get applied (in my case `storage` has an empty AW which causes the `inventory` AW to get applied).

# Expected Behavior
I would expect that all AWs would get applied to the testing project

# Actual Behavior
Only the fist AW (with atleast one entry) in the `includedProjects` array gets applied. Every other AW gets ignored which leads to `java.lang.IllegalAccessError`

# Note

I understand that this is an edge case caused by my project structure but i would be grateful if the behavior would be changed to resolve this issue.

# Env Information
```
Architect Plugin: 3.4.159
Architectury Loom: 1.7.412
```

**Comment by Juuxel** [comment]
This is intentionally disabled in the related upstream code from Fabric Loom:
https://github.com/architectury/architectury-loom/blob/f79827465cf8a70a908bb39990c46dbd50decea7/src/main/java/net/fabricmc/loom/configuration/accesswidener/AccessWidenerJarProcessor.java#L78-L84

(I don't know why, but it probably caused some bug.) I think we should match Fabric's behaviour here, so any changes should be done upstream.

**Comment by Juuxel** [comment]
To expand on the analysis: usually the loader would still apply the AWs from the other modules at runtime (this is what Fabric does), but FML obviously doesn't know what AWs are and can't apply them. Since AW → AT conversion takes place in `remapJar`, NeoForge crashes in dev.

I think the best solution is to have a separate AT, it's sadly unlikely we'll support this edge case (the AW code would need a rework).
