### ISSUE TITLE
No Class Definition Found Error when depending on a mod with JIJ

### ISSUE THREAD

**Issue by gamma-delta** [architectury/architectury-loom#236]
I have a library mod, PAUCAL, that uses Architectury and bundles Jankson, using the `include` config. The jars that it produce work in a runtime environment.

However, I'm trying to depend on PAUCAL in another mod I'm working on. At runtime, I'm getting a `NoClassDefFoundError: blue/endless/jankson/Jankson`. (Logs are attached here: https://mclo.gs/ghyaCtO)

The issue was mentioned in (sigh) [this Discord post in the Architectury discord server](https://discord.com/channels/792699517631594506/1157835955680583800/1157835955680583800); including Jankson directly does fix the problem. However this seems really error-prone and awful to have to sync dependencies across *two* projects, and the whole point of Jar-in-Jar is to not have to worry about this kind of thing.

So, I would like it if depending on something with a jar-in-jar could properly access the JiJ-ed stuff. (@object-Object managed to fix this at some point but she can't figure out how, so if there is an intended way to fix this, that would be nice to know either.)

**Comment by wagyourtail** [comment]
Publish to a maven so theres a proper dependencies list in the metadata, instead of using the modrinth or curseforge one.

Iirc there also used to be a way to just extract nested jars in loom, but im not seeing that on the fabric wiki, so maybe upstream removed it

**Comment by gamma-delta** [comment]
I am.

**Comment by wagyourtail** [comment]
How, i dont see any publish blocks in its build gradle

**Comment by Juuxel** [comment]
This is how nested jars behave in upstream Loom, we're not planning to change it here.
