### ISSUE TITLE
Can't import NeoForge 21.3.36-beta or newer

### ISSUE THREAD

**Issue by VidTu** [architectury/architectury-loom#249]
Starting with NeoForge 21.3.36-beta (https://github.com/neoforged/NeoForge/commit/9c533c2ea899f4c68f444dfa51f5c02d7cddf05d), Architectury Loom can't import (patch) NeoForge project. NeoForge 21.3.35-beta works just fine.

Logs and project files: https://gist.github.com/VidTu/ac64eb74b1ea734b582e26f34e781d47

**Comment by HappyRespawnanchor** [comment]
Fixed in #250

**Comment by VidTu** [comment]
Oh that's cool 👍

###### For whoever encounters this issue, you might need to use `./gradlew --refresh-dependencies` if you're using non-exact versions like "`1.7-SNAPSHOT`" to update plugins version cache.
