### ISSUE TITLE
0.8 doesn't put version number into mojmap file

### ISSUE THREAD

**Issue by KosmX** [architectury/architectury-loom#25]
https://github.com/architectury/architectury-loom/blob/29822d09116670ba41d3c0e3e54e95aedf703519/src/main/java/net/fabricmc/loom/configuration/providers/mappings/MojangMappingsDependency.java#L136
I think, somewhere here

the loom does not put the MC version number into the mappings file
If I use 1.16.5 and I want to use 1.17, I have to do refresh dependencies, or delete the `~/.gradle/caches/fabric-loom/mappings.tiny-final.jar` file...

**Comment by Juuxel** [comment]
https://github.com/architectury/architectury-loom/blob/29822d09116670ba41d3c0e3e54e95aedf703519/src/main/java/net/fabricmc/loom/configuration/providers/mappings/MojangMappingsDependency.java#L132

See the line above, the mappings are put into their specific directory.

**Comment by KosmX** [comment]
It can put it there, but it will be in `~/.gradle/caches/fabric-loom/mappings.tiny-final.jar` that file, and that file doesn't contain the version number...

I'm not a loom dev, I just have a nonsense issue. My project is or working on 1.16 but not on 1.17, or it's working on 1.17 but not on 1.16. After a bit experimenting, I've found that cache file, what causes the issue.

**Comment by KosmX** [comment]
Fixed with #26
