### ISSUE TITLE
Read NeoForge ats from userdev config

### ISSUE THREAD

**Issue by Juuxel** [architectury/architectury-loom#253]
Relevant discussion from the NeoForge discord: https://discord.com/channels/313125603924639766/570666026077913098/1314619513525768202

**Comment by qyl27** [comment]
After my inspection, this is the root issue of #229, we couldn't add another at/aw for forge/nf projects if we have an aw in the common project.  
I manually merge these two files for forge/nf projects in my workaround.

**Comment by Juuxel** [comment]
@qyl27 As far as I can tell, this is unrelated to #229. The crash there occurs because
- the decompiler cache is making `genSources` only decompile the NeoForge classes
- our patch removes all Neo/Forge line numbers from the line number map, leaving it empty:
https://github.com/architectury/architectury-loom/blob/f79827465cf8a70a908bb39990c46dbd50decea7/src/main/java/net/fabricmc/loom/task/GenerateSourcesTask.java#L452-L475
Fixing the TODO in `GenerateSourcesTask` would fix your bug (but it's still not a priority since access widening loader classes isn't something we support).

**Comment by Juuxel** [comment]
Fixed in 1.9.

**Comment by qyl27** [comment]
Oh, now I see, thanks a lot for your explanation.
