### ISSUE TITLE
Interface Injection not working

### ISSUE THREAD

**Issue by ZZZank** [architectury/architectury-loom#255]
Injected interfaces will be added to sources, but Java compiler cannot recognize them, reporting `symbol not found` when injected methods are used:

<img width="920" alt="Clip_20241218_233015" src="https://github.com/user-attachments/assets/973163a4-548c-4316-a923-c187645956de" />

Interface class:
```java
public interface InjectItemStack {
    void exampleMod$doNothing();
}
```

mixin class:
```java
@Mixin(ItemStack.class)
public abstract class MixinItemStack implements InjectItemStack {
    @Override
    public void exampleMod$doNothing() {
    }
}
```

architectury.common.json:
```json
{
  "injected_interfaces": {
    "net/minecraft/world/item/ItemStack": [
      "com/example/examplemod/inerface_injection/InjectItemStack"
    ]
  }
}
```

using ArchLoom 1.7, the latest (`1.9-SNAPSHOT`) is not working as well

**Comment by Jab125** [comment]
You need a default implementation of any methods you are going to be adding via interface injection:

What not to do:
```java
public interface MyInterface {
  void myMethod();
}
```

Corrected:
```java
public interface MyInterface {
  default void myMethod() {
    throw new AssertionError("This shouldn't happen!");
  }
}
```

**Comment by ZZZank** [comment]
It works after adding default method body, thanks!
