### ISSUE TITLE
loom.forge.include not working without fabric.mod.json file in 0.7.2+

### ISSUE THREAD

**Issue by wagyourtail** [architectury/architectury-loom#28]
here's the log
[build-log.txt](https://github.com/architectury/architectury-loom/files/6665261/build-log.txt)
repo I'm building is https://github.com/wagyourtail/jsMacros/tree/forge-1.16.5-j16

**Comment by Juuxel** [comment]
It seems to be this check failing:
https://github.com/architectury/architectury-loom/blob/97bc8dfc4d5cefa11033250c64183ff66aa293b7/src/main/java/net/fabricmc/loom/util/ModUtils.java#L36-L40

**Comment by wagyourtail** [comment]
yep, I'm workarounding it (at least for now) with blank fabric.mod.json file

**Comment by Juuxel** [comment]
Shouldn't be an issue anymore with Forge's JarJar
