### ISSUE TITLE
Issue with working on multiple versions at the same time

### ISSUE THREAD

**Issue by Picono435** [architectury/architectury-loom#37]
Working with multiple Minecraft versions can be really annoying with architecture. Sometimes I need to delete the entire cache just to change from my project that uses Minecraft 1.16 to the one that is Minecraft 1.14. 

**Error logs from example: _(Project with Minecraft 1.14 -> Project with Minecraft 1.16)_**
> Configure project :
Architect Plugin: 3.2.114
Architectury Loom: 0.7.3.159 Build(release #159)
You are using an unstable version of Architectury Loom! Please report any issues found!

> Configure project :common
:remapping minecraft (TinyRemapper, official -> intermediary)
:remapped minecraft (TinyRemapper, official -> intermediary) in 3.632 s
:remapping minecraft (TinyRemapper, official -> named)
Mapping source name conflicts detected:
  blx METHOD h (()Lblx;) -> [blx/method_8389, brw/asItem]
  bah METHOD h ((Laqm;)V) -> [bah/method_5980, aqn/setTarget]
  bsc METHOD a ((Lchn$a;Lfx;)Lfx;) -> [bsc/method_8598, bsc/getHeightmapPos]
  eej METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eej/method_3931]
  efe METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efe/method_3931]
  egn METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egn/method_3931]
  aqs METHOD h ((Laqm;)V) -> [aqn/setTarget, aqs/method_5980]
  efn METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efn/method_3931]
  aqn METHOD h ((Laqm;)V) -> [aqn/setTarget, aqn/method_5980]
  ehh METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehh/method_3931]
  egw METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egw/method_3931]
  eeo METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eeo/method_3931]
  eer METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eer/method_3931]
  egs METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egs/method_3931]
  efd METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efd/method_3931]
  efc METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efc/method_3931]
  buo METHOD h (()Lblx;) -> [brw/asItem, buo/method_8389]
  egz METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egz/method_3931]
  bel METHOD h ((Laqm;)V) -> [bel/method_5980, aqn/setTarget]
  eeq METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eeq/method_3931]
  eex METHOD a ((Laqa;)Lvk;) -> [eex/method_3931, eeu/getTextureLocation]
  egb METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egb/method_3931]
  efx METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efx/method_3931]
  ehk METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehk/method_3931]
  ehr METHOD a ((Laqa;)Lvk;) -> [ehr/method_3931, eeu/getTextureLocation]
  efs METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efs/method_3931]
  egx METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egx/method_3931]
  efq METHOD a ((Laqa;)Lvk;) -> [efq/method_3931, eeu/getTextureLocation]
  bri METHOD a ((Lchn$a;Lfx;)Lfx;) -> [bri/method_8598, bsc/getHeightmapPos]
  eeb METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eeb/method_3931]
  brw METHOD h (()Lblx;) -> [brw/asItem, brw/method_8389]
  egp METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egp/method_3931]
  egi METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egi/method_3931]
  eek METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eek/method_3931]
  eef METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eef/method_3931]
  ehe METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehe/method_3931]
  eep METHOD a ((Laqa;)Lvk;) -> [eep/method_3931, eeu/getTextureLocation]
  ehd METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehd/method_3931]
  eho METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eho/method_3931]
  efg METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efg/method_3931]
  edx METHOD a ((Laqa;)Lvk;) -> [edx/method_3931, eeu/getTextureLocation]
  ees METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ees/method_3931]
  efy METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efy/method_3931]
  eha METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eha/method_3931]
  edw METHOD a ((Laqa;)Lvk;) -> [edw/method_3931, eeu/getTextureLocation]
  efh METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efh/method_3931]
  ega METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ega/method_3931]
  ehi METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehi/method_3931]
  eff METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eff/method_3931]
  efm METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efm/method_3931]
  eft METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eft/method_3931]
  brz METHOD a ((Lchn$a;Lfx;)Lfx;) -> [brz/method_8598, bsc/getHeightmapPos]
  eed METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eed/method_3931]
  efa METHOD a ((Laqa;)Lvk;) -> [efa/method_3931, eeu/getTextureLocation]
  eee METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eee/method_3931]
  ejk METHOD a ((Laqa;)Lvk;) -> [ejk/method_3931, eeu/getTextureLocation]
  eez METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eez/method_3931]
  efk METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efk/method_3931]
  ege METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ege/method_3931]
  egu METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egu/method_3931]
  egl METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egl/method_3931]
  egy METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egy/method_3931]
  eei METHOD a ((Laqa;)Lvk;) -> [eei/method_3931, eeu/getTextureLocation]
  ego METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ego/method_3931]
  egc METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egc/method_3931]
  eeu METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eeu/method_3931]
  egf METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egf/method_3931]
  egm METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egm/method_3931]
  ehl METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehl/method_3931]
  eel METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eel/method_3931]
  eey METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eey/method_3931]
  ehc METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehc/method_3931]
  ceg METHOD h (()Lblx;) -> [ceg/method_8389, brw/asItem]
  ehm METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehm/method_3931]
  bdg METHOD h ((Laqm;)V) -> [aqn/setTarget, bdg/method_5980]
  egq METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egq/method_3931]
  eea METHOD a ((Laqa;)Lvk;) -> [eea/method_3931, eeu/getTextureLocation]
  eem METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eem/method_3931]
  eeg METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eeg/method_3931]
  ehj METHOD a ((Laqa;)Lvk;) -> [ehj/method_3931, eeu/getTextureLocation]
  efu METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efu/method_3931]
  egt METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egt/method_3931]
  efp METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efp/method_3931]
  eeh METHOD a ((Laqa;)Lvk;) -> [eeh/method_3931, eeu/getTextureLocation]
  egr METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egr/method_3931]
  egh METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egh/method_3931]
  efv METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efv/method_3931]
  ehg METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehg/method_3931]
  ehp METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehp/method_3931]
  efi METHOD a ((Laqa;)Lvk;) -> [efi/method_3931, eeu/getTextureLocation]
  egd METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egd/method_3931]
  edy METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, edy/method_3931]
  eec METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eec/method_3931]
  egg METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egg/method_3931]
  egk METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egk/method_3931]
  eev METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eev/method_3931]
  egj METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egj/method_3931]
  efb METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efb/method_3931]
  efl METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efl/method_3931]
  ehn METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehn/method_3931]
  eew METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, eew/method_3931]
  efz METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, efz/method_3931]
  egv METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, egv/method_3931]
  ehf METHOD a ((Laqa;)Lvk;) -> [eeu/getTextureLocation, ehf/method_3931]

**Comment by shedaniel** [comment]
This should be resolved in 0.10.0 with the new file structure
