### ISSUE TITLE
Failed to runClient for Minecraft 1.15.2 Forge 31.2.47

### ISSUE THREAD

**Issue by Windmill-City** [architectury/architectury-loom#4]
`[22:37:14] [modloading-worker-11/ERROR] (FMLModContainer) Failed to create mod instance. ModID: forge, class net.minecraftforge.common.ForgeMod

Caused by: java.lang.RuntimeException: Missing forge version, cannot continue
	at net.minecraftforge.versions.forge.ForgeVersion.<clinit>(ForgeVersion.java:45) ~[?:?]
	... 20 more`

**Comment by shedaniel** [comment]
What version of forge is this? Also can you attach the debug.log from the run/logs/ folder.

**Comment by Windmill-City** [comment]
Forge 31.2.47, debug.log -> https://gist.github.com/Windmill-City/fe11662bdbd6610aed3ba56b5a7e3f6e

**Comment by Windmill-City** [comment]
![image](https://user-images.githubusercontent.com/14292823/106012765-b59b3080-60f6-11eb-85af-21a932fb1266.png)
i tried to use forgegradle, and it provides these vars by Enviroment variables;
and in forge-loom, these variables are provide by program arguments

**Comment by shedaniel** [comment]
I am closing this as your log doesn't show the error
