### ISSUE TITLE
Method Unobfuscated After Updating to Loom 0.10

### ISSUE THREAD

**Issue by TreyRuffy** [architectury/architectury-loom#49]
Ever since upgrading to Arch Loom 0.10, the `ClientBrandRetriever.getClientModName()` method no longer obfuscates correctly.

When mapping with either official Mojang or Yarn mappings and building my mod with the `ClientBrandRetriever.getClientModName()`, it does not obfuscate back correctly on the Forge part of the mod. It works correctly on Fabric.

Upon looking decompiling the mod before porting it to Architectury, I can tell that it is supposed to be `ClientBrandRetriever.m_129629_()`.

This still occurs on the latest (at the time) snapshot of 0.10.0 (0.10.0.176).

Decompiling the Architectury Fabric mod, the mod also does not obfuscate the method, but it works correctly.
Checking the mapped Minecraft jar, the method does have a "DontObfuscate" annotation.
![Screenshot 2021-09-25 011628](https://user-images.githubusercontent.com/17056969/134762626-28f187b1-abf3-4120-a06f-61e7c103491a.png)

**Comment by BloCamLimb** [comment]
This crashes the game in the production environment, with Forge.
