### ISSUE TITLE
TextureUtil, GlConst and GLX are still SRG names

### ISSUE THREAD

**Issue by BloCamLimb** [architectury/architectury-loom#55]
**TextureUtil**, **GlConst** and **GLX** are still SRG names. Only **RenderSystem** and **GlStateManager** are remapped to mojang/parchment names in the development environment.

Forge Extension.

**Comment by shedaniel** [comment]
Adding onto this `add` in ListTag would fail to remap mods from srg to named since there is a mapping with `c add c c` in the srg tiny

**Comment by Juuxel** [comment]
Should be fixed with my SrgMerger rewrite.
