### ISSUE TITLE
Porting 1.16 mod to 1.17

### ISSUE THREAD

**Issue by gohkenytp** [architectury/architectury-loom#56]
I was trying to port forge mode from 1.16 to 1.17 and I came across this:
"You are using an unstable version of Architectury Loom! Please report any issues found!"
Can anyone fix this?

**Comment by Juuxel** [comment]
This is not a bug. The current version of arch loom *is* still a bit unstable (esp. with forge <=1.16), so proceed with caution. Things should mostly work, though.

**Comment by gohkenytp** [comment]
But it causes errors.

**Comment by dvitski** [comment]
If there are errors after that, then I'm afraid that's on you, sorry

**Comment by shedaniel** [comment]
The issue tracker should be reserved for issues, for support enquires we have alternative channels for them (Discord).

I also just enabled discussions on this and other repos that you can also use.
