### ISSUE TITLE
Libraries on the runtime classpath should work without forgeRuntimeLibrary

### ISSUE THREAD

**Issue by Juuxel** [architectury/architectury-loom#58]
Normal dependencies should Just Work™ from the user's perspective without this sort of hackery and a separate configuration.

**Comment by shedaniel** [comment]
Unfortunately this is limited by Forge's new runtime classpath file, this is actually more of a hackery in ForgeGradle as users of FG has to  declare a new configuration themselves and apply to the file

**Comment by Juuxel** [comment]
This is not planned anymore – there is no good way to automatically detect which files should be on the bootstrap classpath.
