### ISSUE TITLE
forge server run config can't run by default

### ISSUE THREAD

**Issue by Yoghurt4C** [architectury/architectury-loom#73]
trying to launch the generated server run config for the forge subproject results in `Exception in thread "main" java.lang.ClassNotFoundException: cpw.mods.bootstraplauncher.BootstrapLauncher`. removing the transfomed `bootstraplauncher` jar from the classpath exclusions inside the run config seems to fix this

**Comment by TropheusJ** [comment]
still an issue on 1.18.2 with arch loom 11

**Comment by MaxNeedsSnacks** [comment]
Can confirm this is an issue in the latest version of arch loom 0.11.0

**Comment by Juuxel** [comment]
Should be fixed with bf7880bfed66e2aa8ef26b2ace36634f91e9ab4d.
