### ISSUE TITLE
mixin/refmap no longer mapping to alternate `targetNamespace`s properly

### ISSUE THREAD

**Issue by wagyourtail** [architectury/architectury-loom#79]
back in like 0.8, toM worked to create "official" (notch) mapped jars with mixins/refmap working properly, some time between then and 0.10 that stopped being the case and the mixin `@shadow` fields are left named, and the refmap is left intermediary, this seems to be caused by the prepping for mixin remapping being moved into the compileJava task at https://github.com/architectury/architectury-loom/blob/dev/0.11.0/src/main/java/net/fabricmc/loom/build/mixin/AnnotationProcessorInvoker.java and hardcoding the output mapping type.

there are 2 possible solutions as I see it:
1. make the remapJar task actually understand how to dynamically remap the mixin file
1. adding targets as available `loom.platform` options (and making that work with arch-plugin)

the problem with 2 being, if people are using custom remapJar tasks to get outputs in multiple formats, it won't work, and is only beneficial to the architectury-plugin layout/environment

**Comment by shedaniel** [comment]
Ideally I would want to fork fabric's mixin compile extension to allow a bigger control on this, but don't have the time for that.

As a temporary fix, I have added the following:
```groovy
loom {
    mixin {
        legacyRemapToNamespace = "official"
    }
}
```
