### ISSUE TITLE
FMJs are generated for Quilt `include`d dependencies when they already have one

### ISSUE THREAD

**Issue by triphora** [architectury/architectury-loom#90]
Title should explain it all.
To repro:
1. Create a quilt subproject
2. Add a fabric dependency and JiJ it
3. Look at the fmj for the fabric dependency after building

It should be the same as the original dependency's fmj but becomes one generated by Loom.
Used for testing: `maven.modrinth:midnightlib:0.4.0` located at `https://api.modrinth.com/maven`

**Comment by Juuxel** [comment]
Should be fixed by e75f1bf9937c7ed4dddc6b3aa51fdba9f0dda78d.
