### ISSUE TITLE
Support Forge Jar-In-Jar (JarJar)

### ISSUE THREAD

**Issue by moechakucha** [architectury/architectury-loom#92]

**Comment by shedaniel** [comment]
More info please? Was it recently added? Don't just create an issue without a description

**Comment by wagyourtail** [comment]
looks like they just merged it https://github.com/MinecraftForge/MinecraftForge/pull/8715

**Comment by moechakucha** [comment]
Similar changes had been done in FG
[MinecraftForge/ForgeGradle#863](https://github.com/MinecraftForge/ForgeGradle/pull/863)
Also has an additional dependency named [JarJar](https://github.com/MinecraftForge/JarJar)
